import React, { useState } from 'react';
import { 
  AlertTriangle, 
  ShieldAlert, 
  Filter, 
  Search, 
  CheckCircle2, 
  Clock, 
  Layers
} from 'lucide-react';
import { FindingCard } from '../components/findings/FindingCard';
import { Severity } from '../types';
import { useApp } from '../context/AppContext';

export const FindingsPage: React.FC = () => {
  const { findings, searchQuery: globalSearch } = useApp();

  const [severityFilter, setSeverityFilter] = useState<string>('ALL');
  const [localSearch, setLocalSearch] = useState<string>('');

  const effectiveSearch = globalSearch || localSearch;

  const filteredFindings = findings.filter((item) => {
    const matchesSeverity = severityFilter === 'ALL' || item.severity === severityFilter;
    const searchLower = effectiveSearch.toLowerCase();
    const matchesSearch = 
      !effectiveSearch ||
      item.title.toLowerCase().includes(searchLower) ||
      item.summary.toLowerCase().includes(searchLower) ||
      item.relatedFile.toLowerCase().includes(searchLower);

    return matchesSeverity && matchesSearch;
  });

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      {/* Header */}
      <div className="pb-4 border-b border-[#1D2939] space-y-1">
        <div className="flex items-center gap-2">
          <span className="font-mono text-xs font-bold px-2 py-0.5 rounded bg-amber-500/10 text-amber-400 border border-amber-500/30 uppercase">
            CORRELATION INTELLIGENCE
          </span>
        </div>
        <h1 className="text-2xl font-bold tracking-tight text-[#F8FAFC]">
          Investigation Findings & Anomaly Flags
        </h1>
        <p className="text-xs text-[#94A3B8] font-mono">
          Explainable behavioral alerts generated by cross-referencing multi-source forensic evidence
        </p>
      </div>

      {/* Filter and Stats Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 rounded-xl bg-[#0D131C] border border-[#1D2939]">
        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-xs font-mono font-bold text-[#94A3B8] flex items-center gap-1.5 mr-1">
            <Filter className="w-3.5 h-3.5 text-blue-400" />
            SEVERITY:
          </span>

          {['ALL', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map((sev) => {
            const isActive = severityFilter === sev;
            return (
              <button
                key={sev}
                onClick={() => setSeverityFilter(sev)}
                className={`px-3 py-1 rounded-lg text-xs font-mono transition-all ${
                  isActive
                    ? 'bg-blue-600/20 text-blue-400 border border-blue-500/50 shadow-forensic font-semibold'
                    : 'bg-[#070A0F] text-[#94A3B8] border border-[#1D2939] hover:text-[#F8FAFC]'
                }`}
              >
                {sev}
              </button>
            );
          })}
        </div>

        <div className="flex items-center gap-3 flex-1 max-w-xs">
          <div className="relative w-full">
            <Search className="w-3.5 h-3.5 text-[#94A3B8] absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              value={localSearch}
              onChange={(e) => setLocalSearch(e.target.value)}
              placeholder="Search findings or files..."
              className="w-full pl-8 pr-3 py-1.5 rounded-lg bg-[#070A0F] border border-[#1D2939] text-xs text-[#F8FAFC] placeholder-[#64748B] focus:outline-none focus:border-blue-500 font-mono"
            />
          </div>
        </div>
      </div>

      {/* Findings List */}
      <div className="space-y-4">
        {filteredFindings.length === 0 ? (
          <div className="p-8 rounded-2xl bg-[#0B1017] border border-[#1E293B] text-center space-y-3">
            <div className="w-12 h-12 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 flex items-center justify-center mx-auto">
              <CheckCircle2 className="w-6 h-6" />
            </div>
            <h3 className="text-sm font-bold font-mono text-[#F8FAFC]">
              {findings.length === 0 ? "No findings." : "No findings match filter."}
            </h3>
            <p className="text-xs text-[#94A3B8] max-w-md mx-auto">
              {findings.length === 0 
                ? "No correlated forensic findings or behavioral anomalies have been identified for this investigation."
                : "No findings match the selected filter criteria."}
            </p>
          </div>
        ) : (
          filteredFindings.map((finding) => (
            <FindingCard key={finding.id} finding={finding} />
          ))
        )}
      </div>
    </div>
  );
};
