"""phase3_models

Revision ID: 3d22624ed3d3
Revises: 9e832ec91138
Create Date: 2026-10-06 09:58:34.802705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d22624ed3d3'
down_revision: Union[str, Sequence[str], None] = '9e832ec91138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('confidence_reason', sa.Text(), nullable=True),
    sa.Column('sequence_summary', sa.Text(), nullable=False),
    sa.Column('event_ids', sa.Text(), nullable=True),
    sa.Column('evidence_ids', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_clusters_case_id'), 'activity_clusters', ['case_id'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step', sa.String(length=64), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_case_id'), 'analysis_jobs', ['case_id'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('anomaly_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('confidence_reason', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('supporting_evidence', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_case_id'), 'anomalies', ['case_id'], unique=False)
    op.drop_index(op.f('ix_evidence_gaps_case_id'), table_name='evidence_gaps')
    op.drop_table('evidence_gaps')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_case_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_risk_histories_case_id'), table_name='risk_histories')
    op.drop_table('risk_histories')
    op.add_column('evidence_relationships', sa.Column('source_id', sa.String(length=64), nullable=True))
    op.add_column('evidence_relationships', sa.Column('target_id', sa.String(length=64), nullable=True))
    op.add_column('evidence_relationships', sa.Column('source_type', sa.String(length=32), nullable=False))
    op.add_column('evidence_relationships', sa.Column('target_type', sa.String(length=32), nullable=False))
    op.add_column('evidence_relationships', sa.Column('explanation', sa.Text(), nullable=True))
    op.alter_column('evidence_relationships', 'source_evidence_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('evidence_relationships', 'target_evidence_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_evidence_relationships_source_id'), 'evidence_relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_evidence_relationships_target_id'), 'evidence_relationships', ['target_id'], unique=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'evidence_relationships', type_='foreignkey')
    op.create_foreign_key(None, 'evidence_relationships', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    op.add_column('findings', sa.Column('confidence', sa.String(length=32), nullable=False))
    op.add_column('findings', sa.Column('confidence_reason', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('what_happened', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('why_detected', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('why_suspicious', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('recommended_next_step', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('supporting_factors', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('related_entities', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('related_timeline_event_ids', sa.Text(), nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.create_foreign_key(None, 'findings', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_reports_sha256_hash'), table_name='reports')
    op.drop_column('reports', 'sha256_hash')
    op.drop_column('reports', 'report_number')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.add_column('reports', sa.Column('report_number', sa.VARCHAR(length=64), nullable=True))
    op.add_column('reports', sa.Column('sha256_hash', sa.VARCHAR(length=64), nullable=True))
    op.create_index(op.f('ix_reports_sha256_hash'), 'reports', ['sha256_hash'], unique=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.create_foreign_key(None, 'findings', 'cases', ['case_id'], ['id'])
    op.drop_column('findings', 'related_timeline_event_ids')
    op.drop_column('findings', 'related_entities')
    op.drop_column('findings', 'supporting_factors')
    op.drop_column('findings', 'recommended_next_step')
    op.drop_column('findings', 'why_suspicious')
    op.drop_column('findings', 'why_detected')
    op.drop_column('findings', 'what_happened')
    op.drop_column('findings', 'confidence_reason')
    op.drop_column('findings', 'confidence')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'evidence_relationships', type_='foreignkey')
    op.create_foreign_key(None, 'evidence_relationships', 'cases', ['case_id'], ['id'])
    op.drop_index(op.f('ix_evidence_relationships_target_id'), table_name='evidence_relationships')
    op.drop_index(op.f('ix_evidence_relationships_source_id'), table_name='evidence_relationships')
    op.alter_column('evidence_relationships', 'target_evidence_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('evidence_relationships', 'source_evidence_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('evidence_relationships', 'explanation')
    op.drop_column('evidence_relationships', 'target_type')
    op.drop_column('evidence_relationships', 'source_type')
    op.drop_column('evidence_relationships', 'target_id')
    op.drop_column('evidence_relationships', 'source_id')
    op.create_table('risk_histories',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('case_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('run_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('previous_score', sa.INTEGER(), nullable=False),
    sa.Column('score_delta', sa.INTEGER(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('findings_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_histories_case_id'), 'risk_histories', ['case_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('action', sa.VARCHAR(length=64), nullable=False),
    sa.Column('case_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_case_id'), 'audit_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('evidence_gaps',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('case_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=32), nullable=False),
    sa.Column('category', sa.VARCHAR(length=64), nullable=False),
    sa.Column('why_it_matters', sa.TEXT(), nullable=False),
    sa.Column('recommended_step', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_gaps_case_id'), 'evidence_gaps', ['case_id'], unique=False)
    op.drop_index(op.f('ix_anomalies_case_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_analysis_jobs_case_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_activity_clusters_case_id'), table_name='activity_clusters')
    op.drop_table('activity_clusters')
    # ### end Alembic commands ###
